"""Added privacy level for post, change Post Model and refactoring how tags is being called

Revision ID: 30cbe9364822
Revises: 499f633a1abd
Create Date: 2019-06-22 13:13:24.151034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cbe9364822'
down_revision = '499f633a1abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('privacy_level', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_posts_privacy_level'), 'posts', ['privacy_level'], unique=False)
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_posts_privacy_level'), table_name='posts')
    op.drop_column('posts', 'privacy_level')
    # ### end Alembic commands ###
