"""re-upgrating the database after downgrating it, add the following: date_added to Post, user_id to init 

Revision ID: 4818b49b73dd
Revises: 5fc1dea03270
Create Date: 2019-05-30 14:10:32.478595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4818b49b73dd'
down_revision = '5fc1dea03270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('post_image_link', sa.String(length=350), nullable=True))
    op.create_index(op.f('ix_posts_date_posted'), 'posts', ['date_posted'], unique=False)
    op.add_column('users', sa.Column('profile_image_link', sa.String(length=350), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'profile_image_link')
    op.drop_index(op.f('ix_posts_date_posted'), table_name='posts')
    op.drop_column('posts', 'post_image_link')
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
