"""Change to uniqueness of links and titles

Revision ID: 75f38c3f555f
Revises: 4818b49b73dd
Create Date: 2019-06-09 16:33:23.229450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f38c3f555f'
down_revision = '4818b49b73dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_image_link',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_image_link',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    # ### end Alembic commands ###
