"""Added public_id and the like system

Revision ID: c8453a54b192
Revises: 6df0646ea1b1
Create Date: 2019-07-11 14:13:04.764134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8453a54b192'
down_revision = '6df0646ea1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postclaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('public_id', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'posts', ['public_id'])
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('public_id', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'public_id')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'confirmed')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'public_id')
    op.drop_column('posts', 'date_updated')
    op.drop_table('postclaps')
    # ### end Alembic commands ###
